build:
  version: "3.0"

spring:
  cloud:
    function:
        definition: updateCommunication
    stream:
      bindings:
        sendCommunication-out-0:
          destination: send-communication
        updateCommunication-in-0:
          destination: communication-sent
    
    rabbitmq:
      host: localhost
      username: guest
      password: guest
      connection-timeout: 10s
      port: 5672

accounts:
  message: "Welcome to Adn Bank accounts related local APIs Defaultss"
  contactDetails:
    name: "Onur Aydın - Developer Defaults"
    email: "onur@adnbank.com Default"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
  redisRateLimit:
    limit: 2
    windowInSecond: 60

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: accounts